package sim;


/**
* sim/AnonymID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Sábado, 7 de Dezembro de 2013 20h44min11s BRT
*/

public final class AnonymID extends org.omg.CORBA.UserException
{

  public AnonymID ()
  {
    super(AnonymIDHelper.id());
  } // ctor


  public AnonymID (String $reason)
  {
    super(AnonymIDHelper.id() + "  " + $reason);
  } // ctor

} // class AnonymID
