package sim;

/**
* sim/SimCorbaServerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Sábado, 7 de Dezembro de 2013 20h44min11s BRT
*/

public final class SimCorbaServerHolder implements org.omg.CORBA.portable.Streamable
{
  public sim.SimCorbaServer value = null;

  public SimCorbaServerHolder ()
  {
  }

  public SimCorbaServerHolder (sim.SimCorbaServer initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = sim.SimCorbaServerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    sim.SimCorbaServerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return sim.SimCorbaServerHelper.type ();
  }

}
