package sim;


/**
* sim/SimCorbaClientOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Sábado, 7 de Dezembro de 2013 20h44min11s BRT
*/

public interface SimCorbaClientOperations 
{
  void update (String message);
} // interface SimCorbaClientOperations
