package sim;


/**
* sim/UserExists.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from sim.idl
* Sábado, 7 de Dezembro de 2013 20h44min11s BRT
*/

public final class UserExists extends org.omg.CORBA.UserException
{

  public UserExists ()
  {
    super(UserExistsHelper.id());
  } // ctor


  public UserExists (String $reason)
  {
    super(UserExistsHelper.id() + "  " + $reason);
  } // ctor

} // class UserExists
